services:
  gr-fe:
    build:
      context: . # 현재 디렉토리(root) 에 있는 파일들을 빌드 대상으로 적용
      dockerfile: Dockerfile # 빌드 시 사용할 Dockerfile 파일 지정
    container_name: gr-fe
    ports:
      - "13000:3000"
    volumes:
      - .:/app # 현재 디렉토리(root) 에 있는 파일들을 /app 디렉토리에 마운트
      - /app/node_modules # node_modules 디렉토리는 컨테이너 내부에서 사용되므로 마운트하지 않음
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    tty: true
    stdin_open: true
    restart: unless-stopped
    