services:
  gr-fe:
    build:
      context: . # 현재 디렉토리(root) 에 있는 파일들을 빌드 대상으로 적용
      dockerfile: Dockerfile # 빌드 시 사용할 Dockerfile 파일 지정
    container_name: gr-fe
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '13000:3000'
    volumes:
      - .:/app # 현재 디렉토리(root) 에 있는 파일들을 /app 디렉토리에 마운트
      - /app/node_modules # node_modules 디렉토리는 컨테이너 내부에서 사용되므로 마운트하지 않음
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    env_file:
      - .env
      - .env.development
    tty: true
    stdin_open: true
    restart: unless-stopped
    command: tail -f /dev/null # npm run restart를 위해 추가. npm run dev가 pid 1번이 아니게 함
    networks:
      - private-network

networks:
  private-network:
    external: true
